### PR TITLE
Nyan overcharge Sounds

### PR DESCRIPTION
**Pull request by M3RT1N99**

### CODE REVIEW

**Comment by Garanas** [comment]
You could also maybe spawn the looped version when the projectile is created so that it looks as long as the projectile lives, then use the short version on impact

**Comment by M3RT1N99** [comment]
This was my idea too, but I need to try on the script, never done this before

Do you have the same problem where the cat won't spawn for you?

**Comment by Garanas** [comment]
Want me to take a look at the script for you?

**Comment by M3RT1N99** [comment]
> Want me to take a look at the script for you?

Would be good, i now just simply added  
`	Audio = {
        Bank = 'Impactnyan',
        Cue = 'NyanLoop',
        -- LodCutoff = 'Weapon_LodCutoff',
    },`
to the effect blueprint  and testing it now

**Pull request closed without merging**
